# Generated by Django 6.1 on 2026-09-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='atricle',
            new_name='article',
        ),
    ]
